name: Build and Push to DockerHub

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'version'
        description: 'Version of the docker image (ex. 0.3.0)'
        # Default value if no value is explicitly provided
        default: '0.3.0'
        # Input has to be provided for the workflow to run
        required: true
  # push:
  #   # branches: [ main ]
  #   tags:
  #   - 'v*'
  
  #pull_request:
  #  branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

env:
  REGISTRY_GITHUB: ghcr.io
  REGISTRY_DOCKERHUB: andreee94
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

##########################################

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY_DOCKERHUB }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta_dockerhub
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY_DOCKERHUB }}/${{ env.IMAGE_NAME }}
        tags: |
          latest
          ${{ github.event.inputs.version }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta_dockerhub.outputs.tags }}
        labels: ${{ steps.meta_dockerhub.outputs.labels }}

##########################################
