name: Manually Test the Code

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

env:
  REGISTRY_GITHUB: ghcr.io
  REGISTRY_DOCKERHUB: andreee94
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

##########################################

    - name: Create secret.yaml file
      run: |
          echo "$SECRET" >> testdata/freenom-solver/secret.yaml
          wc -l testdata/freenom-solver/secret.yaml
      shell: bash
      env:
        SECRET : ${{secrets.FREENOM_ACCOUNT_SECRET}}

    - name: Check secret
      run: ls -lah testdata/freenom-solver

    - name: Go version
      run: go version

    - name: Run Test
      run: TEST_ZONE_NAME="andreee94.ml." make test
      env:
        SECRET : ${{secrets.TEST_ZONE_NAME}}

    - name: Clean Test
      run: make clean

##########################################
