name: Manually Build and Push Docker Images

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

env:
  REGISTRY_GITHUB: ghcr.io
  REGISTRY_DOCKERHUB: andreee94
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

##########################################

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

##########################################

    - name: Log in to the Container registry (ghcr.io)
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY_GITHUB }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker (ghcr.io)
      id: meta_github
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY_GITHUB }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image (ghcr.io)
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta_github.outputs.tags }}
        labels: ${{ steps.meta_github.outputs.labels }}

##########################################

    - name: Log in to the Container registry (DockerHub)
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker (DockerHub)
      id: meta_dockerhub
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMAGE_NAME }}

    - name: Build and push Docker image (DockerHub)
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta_dockerhub.outputs.tags }}
        labels: ${{ steps.meta_dockerhub.outputs.labels }}

    # - name: Sync DockerHub Readme (DockerHub)
    #   uses: ms-jpq/sync-dockerhub-readme@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
    #     readme: "./README.md"
        # repository: ${{ env.IMAGE_NAME }}

    - name: Sync DockerHub Readme (DockerHub)
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${{ env.IMAGE_NAME }}
        readme-filepath: ./README.md
        
##########################################
